### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jcurl** [jcurl/RJCP.DLL.Log#3]
```
First Chance Exception (System.IndexOutOfRangeException): Index was outside the bounds of the array.
   at RJCP.Diagnostics.CrashReporter.FirstChanceExceptionHandler(Object sender, FirstChanceExceptionEventArgs args)
   at RJCP.Diagnostics.Log.Dlt.Args.HexConvert.ConvertToHex(StringBuilder strBuilder, ReadOnlySpan`1 buffer, Boolean upper)
   at RJCP.Diagnostics.Log.Dlt.Args.NonVerboseDltArg.ToString()
   at RJCP.Diagnostics.Log.Dlt.Args.NonVerboseDltArg.Append(StringBuilder strBuilder)
   at RJCP.Diagnostics.Log.DltTraceLine.BuildArgumentText()
   at RJCP.Diagnostics.Log.DltTraceLine.ToString()
   at RJCP.App.DltDump.Application.FilterApp.WriteLine(DltTraceLineBase line, Boolean showPosition)
   at RJCP.App.DltDump.Application.FilterApp.LoopFilter(ITraceReader`1 decoder, Constraint filter)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at RJCP.Diagnostics.Log.TraceReader`1.GetLineAsync()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

```
Program: Unhandled exception
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RJCP.Diagnostics.Log.Dlt.Args.HexConvert.ConvertToHex(StringBuilder strBuilder, ReadOnlySpan`1 buffer, Boolean upper)
   at RJCP.Diagnostics.Log.Dlt.Args.NonVerboseDltArg.ToString()
   at RJCP.Diagnostics.Log.Dlt.Args.NonVerboseDltArg.Append(StringBuilder strBuilder)
   at RJCP.Diagnostics.Log.DltTraceLine.BuildArgumentText()
   at RJCP.Diagnostics.Log.DltTraceLine.ToString()
   at RJCP.App.DltDump.Application.FilterApp.WriteLine(DltTraceLineBase line, Boolean showPosition)
   at RJCP.App.DltDump.Application.FilterApp.LoopFilter(ITraceReader`1 decoder, Constraint filter)
   at RJCP.App.DltDump.Application.FilterApp.Run()
   at RJCP.App.DltDump.View.FilterCommand.Run()
   at RJCP.App.DltDump.View.CommandLine.Run(String[] arguments)
   at RJCP.App.DltDump.Program.Main(String[] args)
```

**Comment by jcurl** [comment]
@robma Potential fix with ad5a2ed59a0c755286a224f5cff1d74ff302bbc8 (may need cleanup). Try the binary:
[dltdump-1.0.0~gad5a2ed+20220324.zip](https://github.com/jcurl/RJCP.DLL.Log/files/8344586/dltdump-1.0.0.gad5a2ed%2B20220324.zip)
